### ISSUE TITLE
O2.5.2: Generalize coupling and surface fluxes to accommodate full land model

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaCoupler.jl#1031]
# The Climate Modeling Alliance
### Purpose
> O2.5.2: Generalize coupling and surface fluxes to accommodate full land model, including:
> - component models using different timesteps
> - identify and implement all flux exchanges needed for more complex model
> - verified correct surface flux calculations, based on unit testing and comparison to observations

This works towards O2.5:
> O2.5 Couple the land surface model with soil/canopy/snow to atmosphere model and update surface flux computations to enable fractional cover with land properties (e.g., snow and canopy). [Possibly move up if needed for good AMIP.]

### Cost/Benefits/Risks
costs: developer time, larger coupler codebase to handle more cases
benefits: more generalized coupling, which will help us prepare for coupling atmosphere + ocean
risks: we don't know yet exactly what changes will be needed to include the more complex land model

### People and Personnel
- Lead: @juliasloan25 
- Collaborators/Reviewers: @akshaysridhar @kmdeck 
- Reviewers: @Sbozzolo 

### Components
- Use different timesteps for each component model
- Identify and document flux exchanges needed for full land model (to and from atmos)
- Implement any flux exchange methods we don't have get (`get_field`, `update_field` functions)
- Verify surface flux calculations, using unit testing, comparison to observation, and coupled model stability

### Inputs
- Existing coupler infrastructure
- Documentation of which fields are expected to be provided by surface models and atmosphere models

### Results and Deliverables
- Able to run coupled atmosphere and full land model simulations (not necessarily stable yet - see O2.5.4)
- Updated documentation of which fields are expected to be provided by surface models and atmosphere models

#### - surface flux calculation
Current
- called in Atmos

Proposed change
- call from Land or Coupler for each land component, then combine with weighted average

#### - `partitioned_turbulent_fluxes!`
note that we can't use the combined turbulent fluxes with the full land model (can't combine land and ocean states when land has multiple states to keep track of - soil, snow, canopy)
Current
- loop over each surface model
- get `surface_thermo_state` and compute surface fluxes of each surface model
- in the full land model, we compute the surface fluxes for each component of the land model, and return a weighted average of these

Proposed change
- idea: instead of getting `thermo_state_sfc` in `partitioned_turbulent_fluxes`, get `thermo_state` and `weights` for each component of land model. Call SF and calculate fluxes for each of these, then combine with provided `weights`.
- idea: Land isolates surface flux calculations to one function (e.g. `get_surface_fluxes`), which is accessible by the coupler. This function takes in thermodynamics parameters and atmos thermodynamic state, and can be used with a prescribed or modeled atmos. After each atmos step, call this function with the latest atmos state (as a callback) and use the returned updated fluxes for the next step.
  - For conservation, will need to accumulate fluxes across timesteps in atmos
  - Need to keep track of order of operations required for this
  - Equivalent `get_surface_fluxes` for other surface models would replicate what is currently done in `partitioned_turbulent_fluxes` [here](https://github.com/CliMA/ClimaCoupler.jl/blob/fa5f03b326bd8aba62c145ee397b176ea1e2e59f/src/FluxCalculator.jl#L160-L180)
  - question: Do we need to support different conservation with component model timesteps?

#### - momentum fluxes
_TODO_: discuss (needed for atmos)

#### - land exchange fields(`get_field`, `update_field!`)
Current
- bucket provides: air density, area fraction, beta, roughness buoyancy, roughness momentum, surface direct albedo, surface diffuse albedo, surface humidity, surface temperature, energy, water
- bucket receives: air density, liquid precipitation, snow precipitation, radiative energy flux at the surface, turbulent energy flux, turbulent moisture flux

Proposed change
- land provides: same as bucket ?
- land receives: ?

### Remaining Questions
- ClimaCoupler has a function `update_turbulent_fluxes!` that [updates a model's turbulent fluxes](https://github.com/CliMA/ClimaCoupler.jl/blob/e8dbf747e8aea88c5d83dc9fda845497de97279c/src/FluxCalculator.jl#L395-L397) with some input fields. E.g. see bucket implementation [here](https://github.com/CliMA/ClimaCoupler.jl/blob/e8dbf747e8aea88c5d83dc9fda845497de97279c/experiments/ClimaEarth/components/land/climaland_bucket.jl#L256-L263). How will we update the full land model's turbulent fluxes with new values, given that the fluxes are distributed among the components of the land model? Will we do a weighted division (like the opposite of a weighted sum)?

### Tasks
```[tasklist]
### Coupling infrastructure
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/1017
- [x] Identify and document flux exchanges needed for full land model (to and from atmos)
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/1182
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/1180
```

```[tasklist]
### Surface flux calculations
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/1202
- [ ] https://github.com/CliMA/ClimaLand.jl/issues/1038
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/1242
```

### SDI Revision Log
- opened 17 October 2024 by @juliasloan25 

### CC
@tapios @sriharshakandala @charleskawczynski @cmbengue

**Comment by tapios** [comment]
This will be nice to have. (We should only do it after the timestepper is changed to integers, so we do not run into float32 problems.)

**Comment by juliasloan25** [comment]
See also this previous SDI in ClimaLand. It's pretty out of date but has some ideas we may want to include here https://github.com/CliMA/ClimaLand.jl/issues/127

**Comment by juliasloan25** [comment]
This milestone is complete!
