### ISSUE TITLE
O2.5.3: Run single column model coupled runs of ClimaAtmos + ClimaLand soil model

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaCoupler.jl#1032]
# The Climate Modeling Alliance
### Purpose
> O2.5.3: Run single column model (SCM) coupled runs of ClimaAtmos + ClimaLand soil model with different component model timesteps and verify stability.

This works toward O2.5:
>  O2.5 Couple the land surface model with soil/canopy/snow to atmosphere model and update surface flux computations to enable fractional cover with land properties (e.g., snow and canopy). [Possibly move up if needed for good AMIP.]

Setting up and maintaining single column coupled runs of ClimaAtmos and the more complex ClimaLand model is a step towards global coupled simulations. Using the soil model rather than the full soil+canopy+snow model will allow us to break down the complexity further.

### Cost/Benefits/Risks
costs: developer time
benefits: exercising coupler code in a wider range of cases will help point us towards rigidity in the code
risks: there have been some problems with ClimaCore `PointSpace` support in the past, and more may surface as we implement this SCM example

### People and Personnel
- Lead: @juliasloan25 
- Collaborators/Reviewers: @akshaysridhar @kmdeck @szy21 

### Components
- As a first step, run SCM example of coupled ClimaAtmos and bucket (this should be straightforward)
- New land model option in ClimaCoupler.jl
- Extend any flux exchange methods that weren't caught in #1031 
- Add new configuration using soil land model

### Inputs
- Generalized coupler infrastructure from #1031 

### Results and Deliverables
- Experiment in CI running SCM coupled ClimaAtmos and bucket
- Experiment in CI running SCM coupled ClimaAtmos and soil land model
  - Make sure simulations are short enough that they don't increase overall CI time

```[tasklist]
### Tasks
- [ ] Set up SCM coupled ClimaAtmos and bucket
- [ ] Support multiple land model options in ClimaCoupler.jl
- [ ] Extend any flux exchange methods that weren't caught in #1031 
- [ ] Add experiment using soil land model
```

### SDI Revision Log
- opened 17 October 2024 by @juliasloan25 

### CC
@tapios @sriharshakandala @charleskawczynski @cmbengue

**Comment by tapios** [comment]
This looks good to me.

**Comment by juliasloan25** [comment]
this is done in main already
