### ISSUE TITLE
O5.3.1: Update ClimaCoupler driver to separate AMIP and slabplanet drivers and have organized subsections

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaCoupler.jl#1050]
# The Climate Modeling Alliance
### Purpose
The current AMIP driver is quite monolithic and inflexible. This OKR moves towards a more modular, developer- and user-friendly implementation.

### Cost/Benefits/Risks

costs: developer time
benefits: this will make it easier to extend the driver for new use cases, and facilitate coupling with external models 
risks: need to maintain functionality and simulation stability while making changes

### People and Personnel
- Lead: @juliasloan25 
- Collaborators/Reviewers: @imreddyTeja @Sbozzolo 

### Components
- First, modularize the existing driver into the following sections:
  - Argument parsing/configuration setup
  - Initialization of component models, coupling objects, and preallocated fields
  - Initial component model exchange
  - Solve function
  - Postprocessing/diagnostics
- Once this cleanup is satisfactory, we can separate the driver into two: one for AMIP and one for slabplanet

### Inputs
Existing `run_amip.jl` driver and ClimaCoupler code

### Results and Deliverables
- maintain simulation stability
- maintain or improve simulation performance (including time to first execution - TTFX)
- reduce amount of code in `run_amip.jl` driver

### Scope of Work

```[tasklist]
### Tasks
- [ ] Design what we want the driver to look like, and how we can get there from what we have
- [ ] Isolate argument parsing/configuration setup
- [ ] Isolate initialization of component models, coupling objects, and preallocated fields
- [ ] Isolate initial component model exchange
- [ ] Isolate solve function
- [ ] Isolate postprocessing/diagnostics
- [ ] Split driver into AMIP and slabplanet
```

### SDI Revision Log
SDI opened 31 October 2024 by @juliasloan25 

### CC
@tapios @sriharshakandala @charleskawczynski @cmbengue

**Comment by juliasloan25** [comment]
instead of splitting amip/slabplanet drivers, we split amip/cmip drivers. the component model constructors are general enough that the drivers are very short and simple now
