### ISSUE TITLE
O5.4.3 Audit and remove easy-to-remove dependencies

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaCoupler.jl#1051]
We may have some packages being used in ClimaCoupler.jl that we don't need anymore, or that we can easily implement workarounds for. We need to first identify these packages, and then remove them. We can start a list in this issue of any such packages.
```[tasklist]
### Tasks
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/1075
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/1091
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/1067
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/1056
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/1057
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/1101
```
