### ISSUE TITLE
AMIP improvements

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#135]
- WIP

High priority
- [x] long Buildkite runs with current packages
  - [x] #143 
  - [x] Artifacts race condition #145 
- [ ] update for latest features when they become available (incl. topog, EDMF etc)
- [ ] address the unrealistic circulation features (@szy21 tagging you here for more pointers as we proceed)
  - [ ] revisit surface flux formulation
  - [ ] effect of sponge on qt in the stratosphere 
- [ ] performance
  - [ ] unnecessary allocs
  - [ ] re-intro flux accumulation for infrequent coupling
    - [ ] need radiative flux accumulation at each timestep in atmos OR the stepping needs to coincide with coupling dt, so that rad fluxes are constant throughout coupling timestep  #146 
- [ ] check that radiation is correct in conservation checker (small divergence, also check mono remapping) - links to [CA#1079](https://github.com/CliMA/ClimaAtmos.jl/issues/1079)
- [ ] demonstrate restart in buildkite 
- [ ] abstract artifacts
- [ ] use `accumulate_fluxes!` from CA when 0.7.1 is available.

Medium priority
- [ ] ozone 
- [ ] use land snow

Low priority
- [ ] bring back dynamical sea ice

Other minor issues:
- [ ] cs needs to be global for the monthly macro - explore other solutions
- [ ] SST_init is modified with SST_info even with deepcopy
- [ ] replace `if mode_name` statements with dispatches, write better abstractions
- [ ] add spin up for AMIP
- [ ] do nothing for the parts of the domain that are masked out - aware of MPI and fracitonal surfaces  
- [ ] add an energy check for MPI runs
- [ ] revamp reinit! (and extra step, which is necessary to set values to the unitialized cache. In `ODE.jl` this is done as part of `reinit!`)
- [ ] add mse tables
- [ ] add perf tracking tools (e.g. flamegraphs etc)

**Comment by szy21** [comment]
Another thing I forgot to mention during the meeting: It would be good to add or bring back restart capabilities.

**Comment by LenkaNovak** [comment]
to be addressed in #215
