### ISSUE TITLE
AMIP with Partitioned Fluxes

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#276]
# The Climate Modeling Alliance
### Purpose

We need a stable interface with robust checks, so once standalone ClimaAtmos is complete, we can immediately test our AMIP configuration. We will also finalize all large software components that need input from scientists (i.e. partitioned surface fluxes). 

### Cost/Benefits/Risks

b: streamlining AMIP delivery. 

### People and Personnel

- Lead: @LenkaNovak 
- Collaborators: @valeriabarra 
- Reviewers: @juliasloan25 

### Components

- there are two parts:
- 1. update package versions / fix outstanding bugs in existing code ([AMIP Roadmap](https://docs.google.com/document/d/1_pCgfY_wDYobJ5KS9oMULUHkb8Zs6mrQSOzauxB-6vc/edit?usp=sharing) non-optional requirements)
  - once this is complete, the AMIP run can be used as a benchmark again
- 2. enhancements (other features used by AMIP setups)
  - fluxes: revise surface fluxes (also the order of timestepping (e.g. radiation) relative to flux computation in Atmos) + include the option to calculate partitioned fluxes
  - check for masking
  - bring back Slack reports

### Results and Deliverables

- [x] utility to calculate fluxes from multiple surfaces and then combine https://github.com/CliMA/ClimaCoupler.jl/milestone/5
- [x] physical correctness summary to weekly Slack updates https://github.com/CliMA/ClimaCoupler.jl/milestone/6

### QA
- [x] conservation tests pass (e.g. #360 )
- [x] coupled comparable to atmos for performance 
  - [Atmos](https://buildkite.com/clima/climaatmos-longruns/builds/1098#_) v [Coupler](https://buildkite.com/clima/climacoupler-reports/builds/21#01899f17-9bbb-49f6-b6da-c8315d4accc5) like for like comparison (using the same dt and apply_limiters=false):
  - Atmos dt=200s (cpu=32, 22 nodes) → 23h25m
  - Coupler dt=200s (cpu=32, 1 node) → 20h50m
  - Coupler dt=200s, ct_cpl=600 (cpu=32, 2 nodes) → 20h45m
  - Coupler + topo, dt=100s (cpu=32, 1 node)  →  ~40h20
  - Coupler + topo + edmf, dt=100s (cpu=32, 1 node)  →  70days in 20h17
- [x] physical tests (see Buildkite runs for different comparisons, also #355, and Slack `#coupler-report` )
  - reasonable comparison with observations (TOA fluxes, precipitation, circulation metrics), given the Atmos setup ([benchmark](https://buildkite.com/clima/climacoupler-ci/builds/1113)) 

### Task Breakdown And Schedule

1. fig outstanding bugs in existing code ([AMIP Roadmap](https://docs.google.com/document/d/1_pCgfY_wDYobJ5KS9oMULUHkb8Zs6mrQSOzauxB-6vc/edit?usp=sharing) non-optional requirements)
  - [x] #282 [25 April]
  - [x] masking - ensure all tests are implemented and passing for all masking options  #286 [1 May] 
- [x] use most recent ClimaAtmos [15 May]
  - this will be done in #281 in a separate folder. Here we will update those API changes to the main driver, and we'll work together with @valeriabarra to update the general environment and tests. 
- [x] enable a surface flux calculation from the atmosphere (from averaged surface states) and partitioned flux calculation from the Coupler (using individual states) #311 [1 August] 

### SDI Revision Log

- tasks to accomplish the Coupler release were split into two SDIs (WIP)

### CC
@tapios @simonbyrne @cmbengue

**Comment by LenkaNovak** [comment]
Complete
