### ISSUE TITLE
Oceananigans Coupling

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#277]
# (WIP!)

# The Climate Modeling Alliance
### Purpose

- minimal coupling of Clima Ocean and ClimaCore-based models at ~1 deg resolution on cubed sphere meshes, demonstrating the required interfaces and coupler functionality for CMIP. 

- (ideas from https://github.com/CliMA/ClimaCoupler.jl/issues/157)

### Components

- generalised interface for flux exchange (using ideas from #211 and [DoubleTrouble.jl](https://github.com/glwagner/DoubleTrouble.jl/blob/main/examples/two_dimensional_atmosphere_ocean.jl))
- Parallel remapping (using a super-halo) using TR to generate weights https://github.com/CliMA/ClimaCoupler.jl/issues/188
- TempestRemap translation to Julia https://github.com/CliMA/ClimaCoupler.jl/issues/262
- weight generation between conformal and equiangular meshes (extend TempestRemap capability in Julia) https://github.com/CliMA/ClimaCoupler.jl/issues/263
- Spatial memory layout optimization https://github.com/CliMA/ClimaCoupler.jl/issues/261
- Staggering projection done using Oceananigans’s infrastructure

### Inputs

- original TempestRemap code
- ClimaCore interfaces and experiments
- Oceananigans interfaces and experiments
- ClimaComms functionality 

### Results and Deliverables

- new repo storing interface design https://github.com/CliMA/ClimaCoupler.jl/milestone/10
- simplified HeldSuarez repo for testing https://github.com/CliMA/ClimaCoupler.jl/milestone/9
- new TempestRemap.jl package including extension for conformal cubed spheres https://github.com/CliMA/ClimaCoupler.jl/milestone/8
- Buildkite driver coupling Oceananigans, ClimaLSM and a ClimaCore-based atmos model. https://github.com/CliMA/ClimaCoupler.jl/milestone/10

### QA
- should close all issues [here](https://github.com/CliMA/ClimaCoupler.jl/milestone/2)

### Task Breakdown And Schedule

- [ ] Task 1: generalised interface for flux exchange [Greg, Lenka]: Use Oceananigans and ClimaCore to design a Simulations like
  -  [x] Port over code from a Held-Suarez experiments + Make new repo - https://github.com/glwagner/ClimaHeldSuarez.jl
  -  [ ] massage the above into Simulations-like interface
  -  [ ] set up ClimaEarth with Simulations-like interface
  -  [ ] add coupling functionality to ClimaEarth
  -  [ ] enable remapping with staggering 
  -  [ ] add examples to demonstrate Oceananigans and ClimaCore coupling 
- [ ] Task 2: Parallel remapping: enable parallel remapping in ClimaCore + add drivers in ClimaCoupler #188  
- [ ] Task 3: TempestRemap translate and extension for regridding of spherical domains
  - [ ] Backup: Can also try (x)ESMS LLC and equiangular CS? (GISS gnomonic CS and MITgcm LLC example) 
- [ ] Task 4: Spatial memory layout optimization https://github.com/CliMA/ClimaCoupler.jl/issues/261
- [ ] Task 5: Concurrent coupling
  - [ ] Explore/use Julia optimization tools (e.g., async etc) 
  - [ ] Temporal memory layout optimization (leverage methods of DOE, NCAR, OASIS-MCT (+ research more recent methods)

**Comment by LenkaNovak** [comment]
To be tackled as part of O5.1 in ClimaEarth
