### ISSUE TITLE
surface fluxes

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#311]
This issue updates the surface flux handling for the new ClimaCoupler release.  

Branch issue of #276 

## Components
Surface fluxes within the coupler need to be updated for
  - new ClimaAtmos interface (which splits Atmos flux calculation and boundary condition specification). After discussions with the Atmos team, it was decided to calculate fluxes in the coupler in the intermediate term (so that different surfaces can be accounted for)
  - write flux calculating functions 
    - turbulent fluxes calculated for each individual surface (partial flux calculation)
    - radiative fluxes still calculated in the atmosphere, by passing in an average T_sfc
  - convert the flux calculation into a general module in src 
  - write tests for the flux calculating functions

## Tasks
- [x] prototype of the above features [26 May] 
  - in this case, it's difficult to visualize the entire product incrementally, so we will put together a prototype in a draft PR, that will be later split into smaller PRs for better review.  https://github.com/CliMA/ClimaCoupler.jl/pull/296
- [x] split prototype PR and merge changes including the following tests [31 May]
  - [x] update `combine_surfaces!` and `update_surface_fractions!` #317  
  - [x] move push_pull! to src by setting up a `FieldExchange` and `FluxCalculator` modules with tests #321
    - [x] check that there is no unnecessary flux calculation files, adding the corrections for ice cover
    - [x] conservation checks
- [x] update for Atmos 0.15.1 #308 
- [x] cleaner q_sat calculation #330 , https://github.com/CliMA/ClimaCoupler.jl/issues/231, #338 
- [x] add partial flux calculation 
    - [x] implement the remaining piece of the #296 prototype with the partitioned flux functionality
    - [x] check surface flux calculation for all masking options (incl.
https://github.com/CliMA/ClimaCoupler.jl/issues/237 ) #360 
        - masking tested in unit tests of #317

**Comment by LenkaNovak** [comment]
Complete
