### ISSUE TITLE
Update Longruns

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#355]
## Purpose 

We need to revamp our longruns to reflect the current requirements and capabilities of ClimaAtmos. 

## To-do

- [x] adapt the `pipeline.yml`

## QA
- [x] show physically reasonable long runs
![amip_paperplots](https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/e37412d6-fc2d-4606-b30f-8520f38899ef)
- [x] perf: 10h15m for n=64, compared to standalone ClimaAtmos 23h for 400d but with n=64 https://buildkite.com/clima/climaatmos-longruns/builds/1098#_ 
    - note: n64 v n32 not a huge speed up: https://buildkite.com/clima/climacoupler-longruns/builds/199 
    -
