### ISSUE TITLE
O1.6.2.2 (coupler) Physical Components for ClimaCoupler v0.1.0 Release

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#359]
# The Climate Modeling Alliance
### Purpose

Having completed the AMIP Roadmap specification in #276 , we want to complete add additional features as per the PCMDI website (GFDL model specification) and ensure that all of our tests and diagnostics are tailored to the the final product, as outlined in the OCR document. The completion of this SDI will bring the functionality of the Coupler to the release stage. An accompanying sister issue #358 aims to prepare the Coupler's software features (i.e. meeting our usability and performance standards) for the release. 
 

This first Coupler release we will be the prequel to the Oceananigans-compatible version for CMIP in `ClimaEarth.jl`.

### Cost/Benefits/Risks

b: streamlining AMIP delivery. 
b: packaging the Coupler product as a clean and usable package

### People and Personnel

- Lead: @LenkaNovak 
- Collaborators: @juliasloan25 
- Reviewers: 

### Components

- there are two parts:
- 1. update package versions 
- 2. outstanding checks (e.g. revise water conservation)
- 3. additional forcing from observations
- 4. revise Buildkite tests to include better diagnostics and reflect current functionalities and performance metrics

### Results and Deliverables

- [x] physical correctness summary on current AMIP target to weekly Slack updates https://github.com/CliMA/ClimaCoupler.jl/milestone/6

### QA
- conservation tests pass
- coupled with no fluxes comparable to atmos for performance
- physical tests 
  - reasonable comparison with observations (TOA fluxes, precipitation, circulation metrics), given the Atmos setup ([benchmark](https://buildkite.com/clima/climacoupler-ci/builds/1113))

### Task Breakdown And Schedule

```[tasklist]
### outstanding checks
- [ ] #303
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/404
```

```[tasklist]
### DSS all timestepped surface models
- [x] #380
- [x] #381
- [ ] #382
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/435
```

```[tasklist]
### additional forcings from observations
- [x] #318
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/408
- [x] check emissivity (available in atmos as a field, when needed)
```

```[tasklist]
### sea ice
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/402
```

```[tasklist]
### Testing
- [ ] #328
- [x] #400
- [x] revamp benchmark longruns + add unstepped prescribed aquaplanet run as a performance metric https://github.com/CliMA/ClimaCoupler.jl/pull/456
```
