### ISSUE TITLE
O5.1.5 (coupler) ClimaUtilities.jl - shared utility package

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaCoupler.jl#367]
# The Climate Modeling Alliance
### Purpose

There are a few modules originally developed in ClimaCoupler.jl that have become duplicated in multiple packages, namely in ClimaLSM.jl and ClimaAtmos.jl. These include the Regridder and BCReader (FileReader in ClimaLSM). Instead of having this code duplicated and slightly modified in multiple places, we should move them to a central repository, e.g. a new ClimaUtilities.jl.

### Cost/Benefits/Risks
- benefit: easier to maintain; we'll only need to update/extend code in one location rather than in all locations having the duplicate code
- cost: each package has slightly different use cases for these utilities, so we'll need to make them more general to handle each of these cases (more developer time required)

### People and Personnel
- Lead: @juliasloan25 
- Collaborators: @LenkaNovak 
- Reviewers: @kmdeck

### Components
- Add functionality to new package
- Extend modules to handle use cases of all packages currently using them
- Remove functionality from existing packages

### Inputs
- see [ClimaCoupler modules](https://github.com/CliMA/ClimaCoupler.jl/tree/main/src) and [ClimaLSM modules](https://github.com/CliMA/ClimaLSM.jl/tree/main/src/shared_utilities)
  - Regridder in ClimaCoupler <--> Regridder in ClimaLSM
  - BCReader in ClimaCoupler, TimeManager in ClimaCoupler <--> FileReader in ClimaLSM
- see [ClimaCoupler tests](https://github.com/CliMA/ClimaCoupler.jl/tree/main/test) and ClimaLSM [FileReader](https://github.com/CliMA/ClimaLSM.jl/tree/main/test/shared_utilities) and [Regridder](https://github.com/CliMA/ClimaLSM.jl/tree/main/test/standalone/Bucket) tests

The ClimaLSM versions of these modules were originally based on the ClimaCoupler implementations, but have been modified to be more suited to ClimaLSM needs. This included generalizing function names that weren't accurate in the coupler version, as well as removing unneeded and unused (in either package) functionality.

ClimaAtmos also uses the regridding functionality in postprocessing (e.g. [remap_helpers.jl](https://github.com/CliMA/ClimaAtmos.jl/blob/dfae8cb49477d11cde0e093754964c8d88fc0182/post_processing/remap/remap_helpers.jl#L50)) and in data reads in gravity wave tests (e.g. [ogw_3d.jl](https://github.com/CliMA/ClimaAtmos.jl/blob/dfae8cb49477d11cde0e093754964c8d88fc0182/test/orographic_gravity_wave/ogwd_3d.jl)). The Atmos interface has diverged somewhat from our modules, so careful consideration (and collaboration with Atmos) will be needed to come up with a sufficiently general utility. 

`Checkpointer` is another module that could be added and generalized. It works similarly to Atmos, and would enable land to use the same checkpointing feature. 

Note: diagnostics should also be unified, but this will be a larger effort led by @Sbozzolo , so we do not include it in the scope of this issue. 

### Results and Deliverables
We should not see performance or behavior changes, and tests should remain high quality. The major changes will be ease of maintenance of this code, as well as increased readability having these utilities in one place.

### Task Breakdown And Schedule
- [x] Create a new package, ClimaUtilities.jl, and set up the repo. https://github.com/CliMA/ClimaUtilities.jl/issues/2
- [ ] Add modules for each of the currently duplicated modules
  - Regridder https://github.com/CliMA/ClimaUtilities.jl/issues/4
  - BCReader/FileReader https://github.com/CliMA/ClimaUtilities.jl/issues/5
  - TimeManager https://github.com/CliMA/ClimaUtilities.jl/issues/6
  - Checkpointer https://github.com/CliMA/ClimaUtilities.jl/issues/7
- [ ] Unify function interfaces across versions of modules for different packcages
- [ ] Extend module functionality for each user package
  - ClimaCoupler
  - ClimaLSM
  - ClimaAtmos
- [ ] Convert each user package to use this new shared utilities package. Add tests ensuring functionality is as desired

### SDI Revision Log

2 Oct: timelines updated, @juliasloan25 will be out of town for a conference and travel 20/10/23 - 5/11/23, so timelines after this point are delayed

### CC
@tapios @simonbyrne @cmbengue

```[tasklist]
### Tasks
- [x] Create new ClimaUtilities.jl package, set up repo [18 Sept] https://github.com/CliMA/ClimaUtilities.jl/issues/2
- [x] TimeManager module, tests [18 Sept] https://github.com/CliMA/ClimaUtilities.jl/issues/6
- [x] TimeManager tested in user packages [22 Sept] #423
- [x] Regridder module, tests https://github.com/CliMA/ClimaUtilities.jl/issues/4
- [ ] Regridder tested in user packages https://github.com/CliMA/ClimaCoupler.jl/issues/425 https://github.com/CliMA/ClimaLSM.jl/issues/332
- [ ] Checkpointer module, tests https://github.com/CliMA/ClimaUtilities.jl/issues/7
- [ ] Checkpointer tested in user packages https://github.com/CliMA/ClimaCoupler.jl/issues/426
- [x] FileReader module, tests https://github.com/CliMA/ClimaUtilities.jl/pull/5
- [ ] FileReader tested in user packages
```

**Comment by juliasloan25** [comment]
moved to ClimaUtilities.jl - see https://github.com/CliMA/ClimaUtilities.jl/issues/39
