### ISSUE TITLE
O1.5.3c (coupler) Run AMIP with diagnostic EDMF and simple land model

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#389]
# The Climate Modeling Alliance
### Purpose

We need to implement and test the current AMIP configurations in our Coupler-LongRuns Buildkite for tracking performance and physical correctness. We want the output to be a weekly report with selected diagnostics.  

### Cost/Benefits/Risks

b: more transparent tracking of our current setup

### People and Personnel

- Lead: @LenkaNovak 
- Collaborators: 
- Reviewers: 

### Components

- OKR-based diagnostics 
- stabilizing simulations when new Atmos components are available (CO2, anticipating EDMF diagnostic, EDMF prognostic)

### Results and Deliverables

- [x] Buildkite in Coupler-LongRuns on topo, prescribed CO2, sea ice and SST simulation
- [x] Buildkite in Coupler-LongRuns on topo, prescribed CO2, sea ice and SST + diagnostic EDMF simulation

### Task Breakdown And Schedule

```[tasklist]
### Tasks: Phase 1
- [x] bring up to speed with ClimaAtmos config #388 #417
- [x] update to Julia 1.9.3 #307
- [x] update to ClimaAtmos 1.6.1, ClimaLSM 0.3.3 https://github.com/CliMA/ClimaCoupler.jl/issues/433
- [x] Add a performance for atmos standalone (aquaplanet) https://github.com/CliMA/ClimaCoupler.jl/issues/457
- [x] Buildkite in Coupler-Reports on DYAMOND resolution, prescribed CO2, topo, sea ice https://github.com/CliMA/ClimaCoupler.jl/issues/408 and SST simulation Bucket https://github.com/CliMA/ClimaCoupler.jl/pull/460
```

```[tasklist]
### Tasks: Phase 2
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/485
```

```[tasklist]
### Tasks: Phase 3
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/574
```

**Comment by akshaysridhar** [comment]
cc @LenkaNovak 
Target simulation in ClimaAtmos (without topography)
- https://github.com/CliMA/ClimaAtmos.jl/blob/main/config/longrun_configs/longrun_aquaplanet_rhoe_equilmoist_nz63_0M_55km_rs35km_clearsky_tvinsolation.yml

**Comment by LenkaNovak** [comment]
completed

**Comment by akshaysridhar** [comment]
GPU update (topo) in ClimaAtmos is dependent on https://github.com/CliMA/ClimaAtmos.jl/pull/2690
