### ISSUE TITLE
Moist Baroclinic Wave terraplanet with basic MPI

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#39]
## Purpose
- prepare the clean spherical model for implementation with topography
- prepare testbed for performance metrics and diagnostics in AMIP

## Final key result
- Moist Baroclinic Wave terraplanet
    - atmos (simple - vertical diffusion / full) with moisture
    - land (slab) 
    - MPI implementation
    - surface fluxes

## Measure of success 
(literature comparison / conservation / performance benchmark)
- [x] performance comparable to standalone runs
- [x] conservation of tracers 

## Risks
- dependencies on many other repos

## Design, Features and Dependencies
- [x] approved design [here](https://github.com/CliMA/ClimaCoupler.jl/tree/jh_ln/bc_wave_slab/experiments/ClimaCore/bc-wave-slab#readme)
- [x] merge TempestRemap hook [CC-pr#614](https://github.com/CliMA/ClimaCore.jl/pull/614)
- [x] bring back BCs in ClimaAtmos - spatially constant [CA-pr#257](https://github.com/CliMA/ClimaAtmos.jl/pull/257) 
- [x] spatially variable BCs
    - [x] finalize [CC-pr#325](https://github.com/CliMA/ClimaCore.jl/pull/325) ClimaCore PR for BCs specifiable by a `Field` [CC-i#630](https://github.com/CliMA/ClimaCore.jl/issues/630)
    - [x] update BCs in ClimaCoupler to be spatially variable
- [x] allow passing surface variables via `Ya`, for updating BCs (coupler calculates surface fluxes) [CA-pr#258](https://github.com/CliMA/ClimaAtmos.jl/pull/258) / [CA-pr#252-Anna](https://github.com/CliMA/ClimaAtmos.jl/pull/252)
- [x] initial conditions in BC wave [CA-i#256](https://github.com/CliMA/ClimaAtmos.jl/issues/256)
- [x] preliminary visual tests
- [x] MPI - using ClimaComms
    - [x] MPI in ClimaAtmos #[CA-pr#267](https://github.com/CliMA/ClimaAtmos.jl/pull/267) - awaiting [CC-pr#631](https://github.com/CliMA/ClimaCore.jl/pull/631)
    - [x] MPI in ClimaCoupler slab
    - [x] MPI init in Coupler
- [x] stack allocations improvements + different space instance issue [CC-i#640](https://github.com/CliMA/ClimaCore.jl/pull/640) (OPTIONAL)
- [x] add moisture fluxes 
    - [x] implement in ClimaAtmos [CA-pr#282](https://github.com/CliMA/ClimaAtmos.jl/pull/282)
    - [x] implement `SurfaceFluxes.jl` [CA-pr#284](https://github.com/CliMA/ClimaAtmos.jl/pull/284)
    - [x] debug moist GCM (negative moisture)
    - [x] limiters [CC-pr#610](https://github.com/CliMA/ClimaCore.jl/pull/610) (cartesian) (OPTIONAL)
    - [x] limiters (spherical) (OPTIONAL)
    - [x] add in ClimaCoupler 
- [x] add radiation (optional) 
    - [x] gray radiation - [CA-pr#357](https://github.com/CliMA/ClimaAtmos.jl/pull/357/files#diff-77d42fa5b8c7a9209b8baaaf1be4595de596514dfd97e5c6e31336b0c868b1ab)
- [x] conservation tests
- [x] performance checks
- [x] physical tests
- [x] documentation

## Driver PR(s)
- [x] dry ClimaAtmos & slab + conservation checks  (with flux calculation in coupler)   #37
- [x] dry ClimaAtmos & slab + BCs specified by `Fields` + MPI + performance checks (+ revived remap) #48 
- [x] moist ClimaAtmos & slab + performance + `SurfaceFluxes.jl` + physical checks #48 
- [x] clean-up PR
    - introduce coupler-specific interface abstractions #44 
    - substitute the latest version of ClimaAtmos interface (TC.jl, limiters, perf improvements etc)
    - buildkite hook
    - find in literature / produce using existing models coupled cases to compare  

## People
- Lead: @jiahe23 
- Collaborators: @LenkaNovak , @sriharshakandala 
- Reviewers: @akshaysridhar 

## Ideal delivery date
- May 6 2022

**Comment by LenkaNovak** [comment]
completed
