### ISSUE TITLE
LES ClimaAtmos / Oceananigans / ClimaLSM coupling (WIP)

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#391]
# The Climate Modeling Alliance
### Purpose

We need a minimal working example for coupling ClimAtmos, ClimaLSM and Oceananigans, without the complexity of spherical regridding.

### Cost/Benefits/Risks

b: clearer plans for CMIP

### People and Personnel

- Lead:
- Collaborators:
- Reviewers: 

### Task Breakdown And Schedule

```[tasklist]
### Tasks
- [ ] Finalize the ClimaArmos LES [@akshaysridhar]
- [ ] Swap Bucket for slab land and simple atmosphere for ClimaAtmos
- [ ] Hook to the Coupler src
- [ ] Run a benchmark simulation
```

**Comment by LenkaNovak** [comment]
This will be implemented and tracked in ClimaEarth in Q2
