### ISSUE TITLE
Hierarchies paper (WIP)

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#392]
# The Climate Modeling Alliance
### Purpose

This showcases the uniqueness of our framework to bridge gaps in classical hierarchical modeling (e.g. https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2017MS001038 ).

### Task Breakdown And Schedule

```[tasklist]
### Tasks
- [ ] compile a list of showcased simulations
- [ ] draft paper structure
- [ ] implement / run the remaining simulations
- [ ] paper draft
```
