### ISSUE TITLE
Test coupling with topography in a Cartesian domain

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#40]
## Purpose
- using a sea breeze test case, this demonstrates the three-way coupling with topography in the box domain.
- this is a prerequisite for testing topography in a simpler domain before implementing it on the sphere

## Final Key Result
- LES sea breeze test case: 
    - atmos (full)
    - ocean (slab)
    - land (full soil)
    - topography

## Measure of success 
(literature comparison / conservation / performance benchmark)
- [x] stable simulations
- [x] tests comparable to literature **??**
- [x] conservation of tracers

## Risks
- N/A

## Design, Features and Dependencies
- [x] [here](https://github.com/CliMA/ClimaCoupler.jl/blob/as/agu-seabreeze/experiments/ClimaCore/sea_breeze/README.md)
- [x] intermediate `ClimaSimulations` interface implementation 
- [x] spatially-varying boundary application [CC-pr#325](https://github.com/CliMA/ClimaCore.jl/pull/325), [CCi#639](https://github.com/CliMA/ClimaCore.jl/issues/639)
- [x] allow different instances of spaces [CC-pr#640](https://github.com/CliMA/ClimaCore.jl/pull/640) 
- ~axis tensor at boundary - generalize to apply to non-Cartesian vectors (represent in Covariant/ Contravariant) (OPTIONAL)~
[CC-i604](https://github.com/CliMA/ClimaCore.jl/issues/604)
- [x] implementation of topography in ClimaCore (see test cases in Numerics DesignDoc)
    - [x] implementation **CC-pr#??**
- [x] documentation
- [x] buildkite hook

## Driver PR(s)
- [x] sea breeze case #33 
- [ ] clean-up PR 
  - introduce more coupler-specific interface abstractions https://github.com/CliMA/ClimaCoupler.jl/issues/44
  - substitute the latest version of ClimaAtmos interface (TC.jl, limiters, perf improvements, topog etc)
  - documentation update
 
## People
- Lead: @jb-mackay 
- Collaborators: @akshaysridhar  
- Reviewers: @LenkaNovak 

## Ideal delivery date
- 4 June
