### ISSUE TITLE
Enhance AMIP and NCEP paperplots 

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#400]
## Purpose 

We need to facilitate quantitative inspection of the NCEP and AMIP data. 

## To-do

- [x] return plot data
- [x] add diagnostics of total precipitable water (`q_liq_ice`) and turbulent energy surface fluxes (`tubulent_energy_fluxes`)

## QA
- [x] AMIP and NCEP plots in desired format

## Note
- alloc test limit was increased due to the additional accumulated diagnostics `allocs_limit["perf_coarse_single_modular"] = 18280800`
