### ISSUE TITLE
Bring Back Semtner Sea Ice

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#402]
## Purpose 

We want to bring back the Semtner model as a stub for a thermodynamic sea ice model for idealized experiments in the near-term. 

## To-do

- [x] revamp for current ClimaCore
- [x] generalize model interface
- [x] add ClimaCore FieldVector indexing https://github.com/CliMA/ClimaCore.jl/pull/1441 
- [x] add unit test 
- [x] conservation tests
- [x] implement in AMIP driver
- [x] update for ClimaTimeSteppers + dss!
- [x] add docs, including units
- [x] implement in CI

## QA
- global energy conservation (note that the ice model here includes the ocean)
<img width="593" alt="Screen Shot 2023-10-02 at 2 36 24 PM" src="https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/ebdd0a9e-f50e-4743-aa68-42ef3c8cff48">

- global water conservation (note that the ice model here includes the ocean)
<img width="588" alt="Screen Shot 2023-10-02 at 2 36 34 PM" src="https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/88c9b4ee-2539-433a-b82e-4063f44f81ab">

- visual check (`CombinedStateFluxes`, no land)
![Screen Shot 2023-09-08 at 1 44 14 PM](https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/10a6c652-7a61-46ae-bfa5-f5d1f9f39d4f)
- visual check (`PartitionedStateFluxes`, land)
<img width="594" alt="Screen Shot 2023-10-02 at 8 25 09 PM" src="https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/5f68afa6-50c4-47bd-8d3e-a9996cac3406">

spin up video:
https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/cdb70efe-f6a4-42ac-8ec2-5aee6f627ebf

- all unit tests in CI pass (`test/component_model_tests/eisenman_seaice_tests.jl` and `test/flux_calculator_tests.jl`)
