### ISSUE TITLE
Land implement bucket model in Land 

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#41]
## Purpose
- provide a stub for the land model (including ClimaLSM interface) for the first AMIP simulation.
- enable a simplified water store in the land and compare it to the currently implemented hydrology model in a SCM. This will ensure all flux passing interfaces are implemented for the more complex test cases.

## Final Key Result
- coupled RCE SCM: 
    - atmos (full=TC,rad,microphysics[,gravity waves]), 
    - land (slab / full soil(= no canopy)), hydrology (bucket / currently implemented soil hydrology) 

## Measure of success 
(literature comparison / conservation / performance benchmark)
- [x] conservation of tracers
- [x] comparable performance to the standalone run

## Risks
- none

## Design, Features and Dependencies
- [x] approved design [here](https://www.overleaf.com/project/625c5f7677155b314c98eb75), see also  [CLSM-pr#43](https://github.com/CliMA/ClimaLSM.jl/pull/43)
- [x] enable interfaces to modify fluxes externally - ClimaAtmos [#257](https://github.com/CliMA/ClimaAtmos.jl/pull/257)
- [x] enable interfaces to modify fluxes externally - ClimaLSM
- [x] implement simple bucket in ClimaLSM in a standalone setting  [CLSM-pr#50](https://github.com/CliMA/ClimaLSM.jl/pull/50/files/d139f5c216cb21603ec7d7a8926f2932c6f0f8a3..3216f607273270d4d9e2ff3d0d751150264d12b0) replaced by https://github.com/CliMA/ClimaCoupler.jl/pull/57

## Driver PR(s)
- [x] coupled bucket case #57 
- [ ] clean-up PR
  - introduce more coupler-specific interface abstractions https://github.com/CliMA/ClimaCoupler.jl/issues/44
  - substitute the latest version of ClimaAtmos interface (TC.jl, limiters, perf improvements, etc)
  - documentation update, incl. comparison to results in Semtner
  - (look for literature benchmark - e.g., CESM RCE case?)

## People
- Lead: @kmdeck 
- Collaborators: @jb-mackay, @LenkaNovak 
- Reviewers: @yairchn 

## Ideal delivery date
- June 28 2022 (without TC.jl)

**Comment by tapios** [comment]
This is looking good to me. Thanks, @kmdeck! I left some comments in the Overleaf.

**Comment by kmdeck** [comment]
thank you, @tapios ! Is there a chance you didn't recompile after making the comments? Looking at the history, I see only a minor change (a space) from your edits...

**Comment by kmdeck** [comment]
@tapios one follow up question - Is the depth of the soil used for computing soil moisture (1m in Manabe) the same as the depth of the soil used in computing the soil temperature? Looking at the slab land code in the coupler repo, they take the depth of the soil to be 100m, and the temperature at the depth to be 280K. 

For soil moisture, we work with `W`, rather than theta - you would just need the depth to convert between them, but this is not necessary to solve the system of equations. It seems like the depth of the soil layer used for moisture implicitly affects the choice of `W_f`, as you noted, while the depth of the soil used in the heat equation appears in the heat equation directly, and presumably should be something large where the soil temperature is ~fixed.

**Comment by tapios** [comment]
> @tapios one follow up question - Is the depth of the soil used for computing soil moisture (1m in Manabe) the same as the depth of the soil used in computing the soil temperature? Looking at the slab land code in the coupler repo, they take the depth of the soil to be 100m, and the temperature at the depth to be 280K.

For purposes of computing moisture, we do not need to specify the depth of the soil. We can just interpret your `W` as the depth of the equivalent soil water column, with a maximum depth `W_f` corresponding to the "bucket depth." However, the depth of the soil used for the thermal calculations can be very different. The seasonal cycle penetrates about 7 m into soil, so this is a reasonable depth for us to use (the temperature there is about the local annual average temperature). To get to a constant temperature depth, we'd have to go deeper. So this depth should be independent of the "bucket depth".

> For soil moisture, we work with `W`, rather than theta - you would just need the depth to convert between them, but this is not necessary to solve the system of equations. It seems like the depth of the soil layer used for moisture implicitly affects the choice of `W_f`, as you noted, while the depth of the soil used in the heat equation appears in the heat equation directly, and presumably should be something large where the soil temperature is ~fixed.

Yes, that's right.
