### ISSUE TITLE
Implement prescribed sea ice

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#42]
## Purpose
Implement sea ice (prescribed sea ice thickness [e.g., 2 m] and sea ice concentration, with[ Semtner](https://www.atmosp.physics.utoronto.ca/people/guido/PHY2502/articles/seaice-landice/AJSemtner_1976.pdf) 0-layer sea ice model (simplified as in[ this code](https://github.com/sally-xiyue/fms-idealized/blob/sea_ice_v1.0/exp/sea_ice/srcmods/mixed_layer.f90), documented in[ this paper](https://agupubs.onlinelibrary.wiley.com/doi/pdf/10.1029/2021MS002671)) 

## Final Key Result
- Smooth moist BW with multiple surfaces: atmos (full) + land (slab) + hydrology (bucket) + ocean (prescribed) + sea ice (prescribed) with a land-sea mask

## Measure of success 
(literature comparison / conservation / performance benchmark)
- [x] physical tests
- [x] conservation of tracers
- [x] performance comparable to standalone run

## Risks
- no domain expertise but should be ok

## Design, Features and Dependencies
- [x] approved design [here](https://github.com/CliMA/ClimaCoupler.jl/blob/fd1eb0bc220ad34541db15478a6bb4d247a2f623/experiments/ClimaCore/sea-ice/README.md)
- [x] implement sea ice in a SCM [#46](https://github.com/CliMA/ClimaCoupler.jl/pull/46)
- [x] use the sea ice model on sphere with a land-sea mask
- [x] use prescribed ocean `T_sfc` and `h_i` data
- [x] pull sea ice out of the test case to the coupler's `src`
- [x] sea-ice mask
- [x] add file reader if want to replace sea-ice concentration and depth with prescribed values, e.g. like in CESM AMIP (https://www.cesm.ucar.edu/models/ccsm4.0/cice/doc/node23.html)
- [x] add ocean Q flux

## Driver PR(s)
- [x] sea ice in a SCM  [#46](https://github.com/CliMA/ClimaCoupler.jl/pull/46)
- [x] sea ice on sphere - prescribed #50 , #51 
- [x] sea ice on sphere - dynamical [#69](https://github.com/CliMA/ClimaCoupler.jl/pull/69)
- [x] clean-up PR
  - introduce more coupler-specific interface abstractions https://github.com/CliMA/ClimaCoupler.jl/issues/44
  - substitute the latest version of ClimaAtmos interface (TC.jl, limiters, perf improvements, etc)
  - documentation update, incl. comparison to results in Semtner

## People
- Lead: @LenkaNovak 
- Collaborators: @jb-mackay , @akshaysridhar 
- Reviewers: @szy21 @kmdeck 

## Ideal delivery date
- May 6 2022

**Comment by LenkaNovak** [comment]
complete, sea ice to be moved in #212
