### ISSUE TITLE
Coupler-specific Interface

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#44]
# Purpose

A formal coupler-specific interface is missing. We need to re-introduce concepts from `CouplerMachine.jl` to formalize the coupling and information passing between different models for the `ClimaCore`-related codebases. 

# Final Key Result
A lightweight coupler interface that users feel comfortable using when building coupled models going forward.
- simplified, readable driver files
- automatic remapping
- mock simulations interface

# Sketch of Needed PRs

- [x] Reset current interface to basics "blank canvas" #52
- [x] Introduce simple simulations interface (wrapping integrators) #53 
- [ ] Auto-building remap operators #67
- [x] get with remapping #58 #76 
- [ ] put with remapping #65
- [x] Implement push and pull methods #83 
- [ ] Coupled timestepper standardization
- [ ] Diagnostic/utility standardization
- [ ] `coupler_utils` to src #134 
- [ ] streamline slab types

# Driver PRs
- Use sea-breeze as testbed and example of new interface

# Current Design
- `ComponentModelSet`: struct (or Tuple), listing all required model components
```
struct ComponentModelSet{M} <: AbstractComponentModelSet 
    models::M
end
```

- `CouplerSimulation`: coupler and component model simulation info. `coupler_fields ` is optional and may contain any relevant fields or their subsets (e.f. boundary fields)
```
struct CouplerSimulation{CS, CF, RW, S, L} <: AbstractSimulation
    coupler_solver::CS
    coupler_fields::CF
    regrid_weights::RW
    simulations::S
    logger::L
end
```

- `CouplerSolver`: time stepping information, unknown by the model components. Current implementation `stepping = Leapfrog()` and `mode = Sequential()`
```
struct CouplerSolver{T, TS, S, M} <: AbstractSolver
    dt::T
    timespan::TS
    stepping::S
    mode::M
end
```

- `init`: iterate over all component models' init functions, with externally customizable ICs, BCs, dt (requirement for ClimaAtmos, ClimaSLM, Oceananigans)
```
function init(cm:: ComponentModelSet)
    # iterate over all component models' init functions
        # spatial info (domain / spaces / models, etc)
        # specify BCs
        # specify ICs
        # init integrators
    # check compatibility
        # dt for each model not to exceed CFL
        # unit checks
    # regridding init (if applicable)
        # generate all regridding weight maps
    #@showinfo 
    return CouplerSimulation
end
```

- `push!`: pushes onto coupler storage - use sparingly only for fields that cannot be extracted from the ModelComponents (e.g., when accumulating fluxes within the coupler). Each item in `targets` or `sources` needs to have the field (and eventually units) and associated model attached to it, so that the correct regridding weights. 
```
function push!(m::ModelComponent, targets, sources) 
    # iterate over all source/target pairs
    target = regrid(source) 
    # perform coupler-internal accumulations
end
```

- `pull`: each model /coupler pulls out and regrids what it needs from elsewhere before it steps
```
function pull(m::ModelComponent, target, source)
    # iterate over all source/target pairs
    target = regrid(source) 
    # include any necessary (e.g. unit) conversions
end
```

- `run`: time integration loop what loops over all component models
```
function run(::CouplerSimulation, :: ComponentModelSet, ::Sequential) 
    # timer start
    # loop
        pull()
        step!()    
        push!()
        logger() # diagnostic . metrics
    # timer end
end
```

- `conservation_checks`
```
function conservation_checks(s::CouplerSimulation)
    # s.logger()
    # global_energy_conservation(s)
    # global_mass_conservation(s)
end
```

# Caveats
- ClimaAtmos interface is changing. It is unclear whether it will converge to the Oceananigans-based CimaSimulations interface. The best option is to develop on the basis of what all previous options have in common and keep as few interface layers as possible. 

# Suggested assignees
- Ben, Lenka

# Suggested reviewers
- Akshay, Simon

**Comment by jb-mackay** [comment]
> `push!`: pushes onto coupler storage - use sparingly only for fields that cannot be extracted from the ModelComponents (e.g., when accumulating fluxes within the coupler). Each item in targets or sources needs to have the field (and eventually units) and associated model attached to it, so that the correct regridding weights.

https://github.com/CliMA/ClimaCoupler.jl/blob/1be239bc0d2912e5caf00b01e07ca6f54eea2625/src/CouplerState/coupler_state.jl#L106

`push!`: pushes coupled fields into the coupler from `model`. Use for _all_ coupled fields that a component needs to provide to other models, accumulated or otherwise. All coupled fields must go through the coupler, which handles all regridding and other standard coupling operations.

Wraps `coupler_put!`s which put a single field in the coupler and look something like:

https://github.com/CliMA/ClimaCoupler.jl/blob/1be239bc0d2912e5caf00b01e07ca6f54eea2625/src/CouplerState/coupler_state.jl#L125-L132

---

> pull: each model /coupler pulls out and regrids what it needs from elsewhere before it steps

https://github.com/CliMA/ClimaCoupler.jl/blob/1be239bc0d2912e5caf00b01e07ca6f54eea2625/src/CouplerState/coupler_state.jl#L83

`pull!`: extracts all needed boundary fields from the coupler (regridded, etc) and updates `model`'s boundaries. `model` should be `step`-ready after a `pull!`.

Wraps `coupler_get`s which get a single field from the coupler and look something like:

https://github.com/CliMA/ClimaCoupler.jl/blob/1be239bc0d2912e5caf00b01e07ca6f54eea2625/src/CouplerState/coupler_state.jl#L93

---

Keeping track of target/source pairs is not explicitly needed -`push!/pull!` are one-way connectors between a model and the coupler.

**Comment by jb-mackay** [comment]
> `CouplerSimulation`: coupler and component model simulation info. coupler_fields is optional and may contain any relevant fields or their subsets (e.f. boundary fields)
> 
> ```
> struct CouplerSimulation{CS, CF, RW, S, L} <: AbstractSimulation
>     coupler_solver::CS
>     coupler_fields::CF
>     regrid_weights::RW
>     simulations::S
>     logger::L
> end
> ```

I think we should call this a `CoupledSimulation`. The regrid weights and coupled fields can be stored together in a `Coupler` object:
https://github.com/CliMA/ClimaCoupler.jl/blob/1be239bc0d2912e5caf00b01e07ca6f54eea2625/src/CouplerState/coupler_state.jl#L28-L35

**Comment by jb-mackay** [comment]
It's not clear to me yet what the best way to set up the `CouplerSolver` will be yet. We definitely want to support the ability to switch between different schemes eventually, though I'm not sure how soon we will want this.

We should discuss what scheme to use for AMIP - Leapfrog? Sequential?

**Comment by jb-mackay** [comment]
On the ClimaAtmos note - meeting the ClimaSimulations interface is a requirement that the coupler is imposing on the model components. This is so there is a standard way of stepping models in the coupled timestepper. I don't think that the refactoring they are doing should affect this, as it is higher level.

**Comment by LenkaNovak** [comment]
to be continued on #211
