### ISSUE TITLE
Update interfaces to match SF v0.8.0

### ISSUE THREAD

**Issue by akshaysridhar** [CliMA/ClimaCoupler.jl#475]
```[tasklist]
### Tasks
- [x] Update `SurfaceValues`, `InteriorValues` > `StateValues`
- [x] Remove redundant aerodynamic roughness coefficients if necessary. Check that `PointValueScheme()` is being used.
- [x] Up ClimaLSM.jl: https://github.com/CliMA/ClimaLSM.jl/pull/362
```
cc @juliasloan25 @LenkaNovak
