### ISSUE TITLE
revamp longruns buildkite pipeline

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#477]
We need to revamp our longruns to reflect the current stable targets in ClimaAtmos. The current target in ClimaAtmos is `longrun_aquaplanet_rhoe_equilmoist_nz63_0M_55km_rs35km_clearsky_tvinsolation` (though the specifications of this may change due to unphysical features - see below). For now we use this current target to setup our testing pipeline. 

## Components
- [x] integration hierarchy - testing that atmos surface initialization is consistent with the coupler surface for coarse aquaplanet, and includes conservation checks (this can be eventually be moved to the second tier CI as part of #406 ). The runs involve
  - `slabplanet_aqua_atmos_sf_nocouple` (atmos fluxes at every RK stage, prescribed SSTs from atmos)
  - `slabplanet_aqua_atmos_sf_couple`  (atmos fluxes at every RK stage, prescribed SSTs from coupler)
  - `slabplanet_aqua_coupler_sf` (coupler fluxes at every coupling step, prescribed SSTs from coupler) 
  - `slabplanet_aqua_coupler_sf_evolve_ocn` (coupler fluxes at every coupling step, slab ocean) 
  - `slabplanet_terra` (coupler fluxes at every coupling step, bucket surface) 
  - `slabplanet_coupler_sf_evolve_ocn` (coupler fluxes at every coupling step, slab ocean, bucket surface) 
- [x] current target tests: idealized surface - for long-run reports and like for like atmos comparison
  - standalone: trigger ClimaAtmos driver with target config from the coupler (coupler does not step this)
  - `slabplanet_aqua_new_target_nocouple` (atmos fluxes at every RK stage, prescribed SSTs from atmos, stepped by coupler)
  - `slabplanet_aqua_new_target` (coupler fluxes at every coupling step, prescribed SSTs from coupler) 
  - `slabplanet_aqua_new_target_evolve_ocn` (coupler fluxes at every coupling step, slab ocean) 
  - `slabplanet_new_target` (coupler fluxes at every coupling step, prescribed idealized SSTs from coupler, evolving bucket, target resolution)
   - `slabplanet_new_target_evolve_ocn` (coupler fluxes at every coupling step, slab ocean, evolving bucket, target resolution) 
- [x] current target tests: AMIP surface - current state of AMIP for long-run reports 
  - `amip_new_target` (AMIP with no topography)
  - `amip_new_target_topo` (full AMIP)
- [x] enable evolving ocean from `.yml` file
- [x] enable toml file specification from the coupler
- [x] add infrastructure in `target` dir for the atmos standalone run
- [x] make surface default init conditions equivalent to atmos

## Tasks
- [x] implement the above components
- [x] introduce default initial conditions that are consistent with those in ClimaAtmos (note, this made the eEisenman sea ice component less stable. For now t_end for this case was decreased, but this will be investigated further as part of #494 )
- [x] stabilize coupled long runs (this was achieved by increasing the thermal capacity, but still yields unphysical circulations. This will be investigated in #485)

## QA
- see builds in the [longrun pipeline](https://buildkite.com/clima/climacoupler-longruns/builds?branch=ln%2Flongruns-nwmi3)
