### ISSUE TITLE
O1.3.5 (Atmos) Prescribe aerosol concentrations

### ISSUE THREAD

**Issue by trontrytel** [CliMA/ClimaCoupler.jl#527]
# The Climate Modeling Alliance
### Purpose

Prescribe the aerosol concentrations based on RCP 4.5 from CMIP 5. 

### Benefits

- We need aerosol optical properties for radiation. (We also need to code a way to compute optical properties from aerosol concentrations, see [SDI](https://github.com/CliMA/CloudMicrophysics.jl/issues/213))
- We need aerosol precursors for cloud droplet activation and ice nucleation in 2-moment microphysics scheme. (The 2-moment scheme is under development. See [SDI](https://github.com/CliMA/CloudMicrophysics.jl/issues/218) and [SDI](https://github.com/CliMA/CloudMicrophysics.jl/issues/215)

### People

- Lead: @trontrytel 
- Collaborators: @LenkaNovak  @szy21 
- Reviewers: 

### Results

Run AMIP simulations with aerosol concentrations read from files.

```[tasklist]
### Tasks
- [ ] Visualize the RCP 4.5 data
- [ ] Store the data on Caltech box
- [ ] https://github.com/CliMA/ClimaCoupler.jl/pull/506
- [ ] Enable prescribing (lat, lon, p) fields
- [ ] Run spherical simulations with prescribed aerosols (no coupling between aerosol and anything) and test that our output diagnostics reproduce the prescribed files
```
### CC
@tapios @simonbyrne @cmbengue

**Comment by trontrytel** [comment]
The RCP 4.5 data is in lon(0, 357.5), lat(-90, 90), sigma pressure (3.5, 992.6), time(56605, 56939) format. 

The dataset does not include surface height. So in order to convert it to height I would have to look for a corresponding topography file. I think it would be easier to just try interpolating along pressure inside the Coupler? 

Here is a couple of plots from the lowest level (fist column Jan-Jun, second column Jul-Dec)

Temperature:
![T](https://github.com/CliMA/ClimaCoupler.jl/assets/1196696/7bb68375-8266-4def-8d82-0a910778355d)

Seasalt:
![SSLT03](https://github.com/CliMA/ClimaCoupler.jl/assets/1196696/61a52c48-f5af-4c87-9ec8-a0b12e082978)

Dust:
![DST03](https://github.com/CliMA/ClimaCoupler.jl/assets/1196696/045cea2f-a225-4a23-bcc8-30b2bef0c94a)

**Comment by trontrytel** [comment]
The data is now on CliMA box under Aerosol_RCP45 folder

**Comment by trontrytel** [comment]
Remember to take a look at https://github.com/CliMA/ClimaAtmos.jl/blob/b26b78badeb98f35aa1870a2b0b119aa6f9566cd/src/parameterized_tendencies/radiation/radiation.jl#L85-L97
