### ISSUE TITLE
Small fixes for conservation

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#568]
## Purpose 

Following the ClimaAtmos and ClimaLSM updates, we need to update the following to retain conservation. 

## To-do

- [x] retain output diagnostic files at the end of the run by default
- [x] use rho_ice where snow (fixes non conservation in main)
- [x] add energy from precipitation approximation - requires (`ᶜS_ρq_tot` to be initialized with 0)
- [x] add asserts to conservation (1e-3 for now) - this will catch any future departures from conservation immediately

# QA
- [x] ensure stable CI
- [x] ensure stable longruns
  - diffusion only still needs stabilizing - following params of [this config](https://github.com/CliMA/ClimaCoupler.jl/blob/7b860c23161b34810cdb41d86459ae44ab6fc423/config/longrun_configs/amip_target_topo.yml)  and [this build](https://buildkite.com/clima/climacoupler-longruns/builds/402)
    - Frierson diffusion breaks for for AMIP and AMIP topo [build](https://buildkite.com/clima/climacoupler-longruns/builds/435#018d6c23-6fef-467a-8122-5d3329805bf2) vs using `vert_diff: true` ([build](https://buildkite.com/clima/climacoupler-longruns/builds/436))
      - we will bring this back once issues with surface properties and atmospheric optical are resolved (O1.5.4)
