### ISSUE TITLE
Improve clear-sky TOA shortwave radiative fluxes

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaCoupler.jl#578]
Currently, the clear-sky TOA SW upwelling radiative fluxes have a global mean bias of ~10 W m^-2. Here are the plots of TOA SW upwelling radiative fluxes in June in simulations and observations (not an apple-to-apple comparison as they are different years, just use it as a reference). The clear-sky SW fluxes are affected mostly by surface albedo, water vapor, aerosols and ozone.
Model:
![image](https://github.com/CliMA/ClimaCoupler.jl/assets/11598433/163e4990-f949-4907-8da7-ac4144d92635) 
CERES:
![image](https://github.com/CliMA/ClimaCoupler.jl/assets/11598433/ec52a3d8-b6ea-48ca-ac60-0d3a6e742694)

```[tasklist]
### Simulation
- [ ] Run a one-year simulation for the same year as CERES observation (e.g. 2001), EDMF not necessary
```

```[tasklist]
### Tasks
- [ ] #577 
- [ ] #527 
- [ ] Add aerosol radiative properties to RRTMGP
- [ ] Prescribe ozone concentration
```

**Comment by szy21** [comment]
The ocean surface albedo is a bit too large, inconsistent with the bias in SW. The bias in SW is likely from too much absorption from water vapor.
![image](https://github.com/user-attachments/assets/983336ed-a8e5-4a4e-92cb-ecd2521d8303)
