### ISSUE TITLE
O1.3.1 Multi-year AMIP simulations comparable to CMIP6 models

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#628]
Tasks to enhance the current AMIP setup for comparison with other models. 

```[tasklist]
### Tasks
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/578
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/2630
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/617
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/619
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/479
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/605
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/723
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/764
```

References:
- [PCMDI model specs](https://pcmdi.llnl.gov/mips/amip/home/Documentation/20gfdl.html#RTFToC33)
