### ISSUE TITLE
Wrap up SURF project to calibrate surface flux parameters using flux tower observations and EKP

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#636]
## Summary of the SURF project
- LES data 
  - although the formulation of the Python LES and the SurfaceFluxes.jl seem to have equivalent definitions, the saved LES output does not seem to be sufficient for like-for-like comparison
    - fluxes correspond to previous timestep, whose states are not saved, so dynamics over the one timestep obscure the outcome from the flux calculations
    - there is a systematic offset between the fluxes calculated between Python LES and the SurfaceFluxes.jl, so even the perfect-parameter model is far from the output fluxes
    - including the offset in the model formulation improves the calibration. 
- FLUXNET data
  - needs some clean up to be usable 

```[tasklist]
### Tasks
- [ ] Wrap up https://github.com/wilsonduan10/ekp/tree/main and write up findings (e.g. corrections of systematic model error - location / scaling moments)
- [ ] implement perfect model in [CalibrateAtmos.jl](https://github.com/CliMA/CalibrateAtmos.jl)
- [ ] Clean up FLUXNET data import (use Land's infractructure)
- [ ] Implement SF pipeline in CalibrateAtmos.jl
```

## References
- SURF outcome: https://github.com/wilsonduan10/ekp/tree/main
- also see Eviatar's work
