### ISSUE TITLE
Improve slack report

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#693]
Our slack #coupler-report channel should be used more effectively to report on the following aspects (each of which should branch out to separate issues):

- AMIP longruns: current model state metrics compared to observations
  - [x] coupler diagnostics compared to NCEP reanalysis 
  - [x] leaderboard point observations plots of target metrics #721, #695 #725 
  - [x] add GPU longruns - pending
    - [x] #607 
    - [x] GPU allocation issue: https://github.com/CliMA/ClimaCoupler.jl/issues/683
- slabplanet longruns: 
    - [x] conservation checks 
- scaling tests results of 1 timestep after initialization in a tabulated format for GPU and CPU (ensure all diagnostics are turned off) - see #705 
  - [x] atmos standalone
  - [x] coupled sim  
- memory footprint summary per component  - see #705 
  - [x] table for CPU usage of CPU and GPU runs
- CPU vs GPU error - see #705 
  - [x] buildkite runs like in land + table 
- build_history for history of total allocations and sim time
  - [x] ~convert to pdf  #721~ scrapped - PDF doesn't show job id. We also tried importing the artifact link, but in the end decided that the interactive html was the easiest way forward. See issue for details. 

Once complete
- [x] add this to the documentation
