### ISSUE TITLE
add coupler summary table

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaCoupler.jl#705]
We want to output a table displaying some information about the current state of the coupler. This table/info should be output to the #coupler-report channel on slack.

The runs will include:
- a CPU atmos-only run
- a GPU atmos-only run
  - config file: [config/gpu_configs/gpu_aquaplanet_diagedmf.yml](https://github.com/CliMA/ClimaAtmos.jl/blob/main/config/gpu_configs/gpu_aquaplanet_diagedmf.yml)
- a CPU coupled (AMIP) run
- a GPU coupled (AMIP) run

For each of these jobs, we will output the following quantities:
- SYPD
- CPU vs GPU state (max, median, and mean of difference, as is calculated in [land](https://github.com/CliMA/ClimaLand.jl/blob/main/experiments/standalone/Bucket/compare_gpu_cpu_output.jl)
  - update: I'll add these in a separate PR, since this is currently being implemented in #614
- allocations at the end of the simulation
  - note that there is no equivalent calculation between CPU and GPU, so these numbers won't be directly comparable

part of https://github.com/CliMA/ClimaCoupler.jl/issues/693

## To Do
- [x] add config files for the 2 coupled runs
  - based on atmos [gpu_aquaplanet_diagedmf.yml](https://github.com/CliMA/ClimaAtmos.jl/blob/main/config/gpu_configs/gpu_aquaplanet_diagedmf.yml)
- [x] add config files for the 2 atmos-only runs 
  - it might be nice to just access these from ClimaAtmos.jl, but I can't find a cpu run that's equivalent to the gpu config
- [x] set up atmos_driver to run from different config files
- [x] add runs to benchmarks pipeline - [ClimaCoupler CPU/GPU Benchmarks](https://buildkite.com/clima/climacoupler-cpu-gpu-benchmarks) (from #673)
- [x] add in SYPD calculation (from #673)
- [x] add in allocation printing  (from #691)
- [x] save these to txt files (as is done with states in #614)
- [x] use PrettyTables.jl to create table displaying info read in from these files
- [x] update benchmarks pipeline to send this table to slack channel

## To Do in separate issues/PRs
- [ ] add atmos-only runs without diagnostic edmf
- [ ] add gpu scaling (1, 2, 4 gpus)
- [ ] add cpu/gpu state comparison columns
- [ ] save output as .pdf rather than .txt (use latex backend for PrettyTables)
