### ISSUE TITLE
O1.9.1 Build simple prototype of atmosphere model calibration pipeline for AMIP simulation

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#726]
# The Climate Modeling Alliance
### Purpose

Build simple prototype of atmosphere model calibration pipeline for AMIP simulation (coarse resolution, with a few parameters) w TOA and precip in loss function. 

This is a sequel to #586 , with a more specific loss function. 

Details to follow. 

### SDI Revision Log

```[tasklist]
### Tasks
- [ ] https://github.com/CliMA/ClimaModules-Derecho/issues/2
- [ ] https://github.com/CliMA/ClimaModules-Derecho/issues/1
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/1149
```
