### ISSUE TITLE
Simple I / O pipeline

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#74]
## Purpose
I/O pipeline coordinated by the coupler is necessary for providing restart files, BC files, model diagnostics, performance metrics and conservation checks for the AMIP run. 

- related to the [CC-i#747](https://github.com/CliMA/ClimaCore.jl/issues/747) issue on standard format

The desired outcome are the following features
- **online** 
  - model-grid dump
    - save checkpoint files containing the fully recoverable uninterpolated state by individual MPI PEs at a desired frequency
    - temporal means (extendable to temporal covariances and other similar stats on model grid)
  - BC field reader and manipulation
  - on-the-fly viz
  - other online metrics: conservation, performance
- **offline** 
  - component model diagnostics:
    - each model needs to write user-defined diagnostics interpolated on the lat/long grid on the fly at a desired frequency
    - basic diagnostics (intermediate solution)   
      - a version of this is already implemented as a callback in ClimaAtmos (code reduction possible, apply to netcdf or add a post processing utility) and needs to be implemented in ClimaLSM 
      - a more comprehensive list following the [CMIP guidelines](https://pcmdi.llnl.gov/CMIP6/Guide/modelers.html#4-model-output-fields) and the [Clima user diagnostics issue](https://github.com/CliMA/ClimateMachine.jl/issues/1596)
          - high priority output: https://github.com/CliMA/ClimateMachine.jl/issues/214 
          -  requirements: https://pcmdi.llnl.gov/mips/cmip3/variableList.html 
          - Cmip6 tables: https://github.com/PCMDI/cmip6-cmor-tables/tree/master/Tables, https://clipc-services.ceda.ac.uk/dreq/index/miptable.html
          - database: https://clipc-services.ceda.ac.uk/dreq/mipVars.html   
      - borrowing concepts of distributed diagnostics from the [DiagnosticsMachine](https://github.com/CliMA/ClimateMachine.jl/blob/9503cbc83eb098f0d92bef72745a1d214175940c/src/Diagnostics/DiagnosticsMachine/DiagnosticsMachine.jl)
    - other metrics: comparison with published benchmarks, MSE tables 

## Cost/Benefits/Risks
- benefit: enables the first AMIP showcase
- risk: diagnostics tend to become complicated very quickly, but here we focus on basic fields only to demonstrate the pipeline

## People and Personnel
- Lead: @LenkaNovak 
- Collaborators: @jiahe23 @sriharshakandala @yairchn @juliasloan25 
- Reviewers: @kmdeck @charleskawczynski  @simonbyrne 

## Components
- **online**
  - model-grid dump 
    - [x] state dump for restart *[Sep]*
      - [x] ~jld2 reader/writer of Y (intermediate solution) already used in ClimaAtmos and CC (e.g. [here](https://github.com/CliMA/ClimaCore.jl)) but it is breaking~ [this was implemented in an older version of CC, but was found to break sporadically on the HPC cluster]
      - [x] parallel hdf5 writer (see [#770](https://github.com/CliMA/ClimaCore.jl/issues/770), avoids duplication of Field info, ability to restart with a different number of PEs)
        - needs to be implemented / tested in:
            - [X] ClimaAtmos
            - ~~[ ] ClimaLSM~~ any variables can now be outputted in the coupler (code implementable in ClimaLSM if needed)
            - [x] ClimaCoupler
              - [x] MPI init in CA ~~https://github.com/CliMA/ClimaAtmos.jl/pull/825~~ fixed by https://github.com/CliMA/ClimaAtmos.jl/pull/889
              - [x] CA race condition with HDF5 writer https://github.com/CliMA/ClimaAtmos.jl/issues/794
                - [x] instability due to new ClimaAtmos interface for surface fluxes
              - [x] include in AMIP MPI driver #129 
    - [x] cache / online diags dump* https://github.com/CliMA/ClimaDiagnostics/issues/1 *[Sep-Dec]*  #122
      - deal with duplicate names 
      - model-specific and custom calculations 
      - distributed 
      - model non-specific functions
      - time averaging and other manipulations (callbacks)
    - [x] monthly save callback *[Sep]*
      - [x] ClimaCoupler #115
  - BC field reader and manipulation
    - [x] ClimaCoupler: read in NetCDF files, e.g., for prescribing SSTs, sea ice, O3, albedo / landuse #88
    - [x] Remapping using tempest remap *[Sep]*
      - [x] mono CC flag https://github.com/CliMA/ClimaCore.jl/pull/895
      - [x] mono CCou test #114 
      - [x] enable `Nq 5` monotone remapping (pending TempestRemap release) CC#[958](https://github.com/CliMA/ClimaCore.jl/pull/958)
    - [x] interpolate linearly in time 
    -~~[ ] parallel online Remapping*  *[NEED RESOURCES]*~~ (lower priority so moving to pipeline-v2)
  - on-the-fly viz *[Oct]*
    - [x] plots of dumped hdf5 data     #122
  - other online metrics 
    - [x] conservation #121 #122 
    - ~~[ ] performance ~~ to be addressed as part of the interface revamp
- **offline** 
  - component model diagnostics
    - [x] remapping
    - [x] custom calculations (low priority) #122 
    - ~~[ ] interpolation to pressure surfaces* *[Simon, Nat]*~~ (lower priority so moving to pipeline-v2)
  - metrics
    - perf + visual comp with published benchmarks* 
      - [x] plots, perf metrics
      - [x] platform *[NEED RESOURCES]* #122 
    - MSE tables
      - [x] ClimaAtmos 
      - ~~[ ] ClimaCoupler *[Nov]* ~~ to be addressed as part of the interface revamp

## Other issues to address
- [x] ClimaAtmos driver updates
  - [x] 06-09-2022 (Julia1.8+SF.jl) #113  
  - [x] update for Atmos0.5.0#132
  - [x] update for ClimaTimeSteppers #133 
- ~~[ ] save at crashed timestep *[NEED RESOURCES]* ~~ (lower priority so moving to pipeline-v2)

## Deliverables
- [x] driver on buildkite end-to-end I/O pipeline for coupled AMIP (the intermediate solutions above only) 
- [x] (stretch) plan for long-term solution (#135 for WIP list)

## Proposed Delivery Date
1 November 2022

**Comment by LenkaNovak** [comment]
All completed. Follow up coming up in #135.
