### ISSUE TITLE
Small performance improvements

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaCoupler.jl#767]
Minor issues found in  https://github.com/CliMA/ClimaCoupler.jl/issues/390 that we want to clean up for better performance.

### Tasks
- [ ] don't pass FT as an argument
- [ ] use `zero(FT)` instead of `FT(0)` to reduce allocations https://github.com/CliMA/ClimaCoupler.jl/pull/1599
- [ ] https://github.com/CliMA/ClimaCoupler.jl/pull/1595
- [ ] https://github.com/CliMA/ClimaCoupler.jl/pull/1768
- [x] remove use of `parent` (except where needed when spaces aren't identical ?)
- [x] make sure no closures over global variables (e.g. `FT`
- [x] limit use of `Val` to only when necessary

some points taken from https://github.com/CliMA/ClimaCoupler.jl/issues/323

**Comment by juliasloan25** [comment]
I don't think any of these will actually improve performance, based on my testing
