### ISSUE TITLE
Doc Week

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#84]
## Purpose
Improve documentation of the current coupler pieces. 

## Current doc-ing effort 
- [ ] Examples
  - ClimaAtmos + ClimaLSM 
    - [x] Sea breeze [Ben, Lenka]
    - [ ] AMIP also as buildkite [Kat - bucket,Jia - diags, Lenka]
      - [x] Bucket docs in ClimaLSM- PR in ClimaLSM 
  - Simple + ClimaCore 
    - [ ] Advection + diffusion column
    - [ ] ClimaCore + Oceananigans
- [ ] DocStringExtensions [Ben]
- [ ] Intro docs for concepts 

### Associated issues / PRs
- https://github.com/CliMA/ClimaCoupler.jl/issues/64
- https://github.com/CliMA/ClimaCoupler.jl/issues/63 
- https://github.com/CliMA/ClimaCoupler.jl/pull/75
 
## People and Personnel
(@ the personnel required/requested to implement the software solution)
- Lead:
- Collaborators:
- Reviewers:

## Components
(Describe the main components of the software solution)

## Inputs
(Describe the inputs to the software solution)

## Results and deliverables
(Summarize of the key results, deliverables, quality expectations, and performance metrics)

## Task Breakdown And Tentative Due Date
(A preliminary list of PRs and a preliminary timeline of PRs, milestones, and key results)
- [ ] Child Issue #1
- [ ] Child Issue #2

## Proposed Delivery Date
(Your best estimate of the date this software solution will be completed)

**Comment by LenkaNovak** [comment]
out of date
