### ISSUE TITLE
O1.5.x Make a good multiyear simulation before 7/4

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaCoupler.jl#847]
### Purpose
We need to show a (good) multiyear AMIP simulation during the VESRI meeting.

### People 
@szy21 @Sbozzolo @juliasloan25 and others

### Target
Resolution: h_elem = 16 (~200km), z_elem = 63
Simulation year: 2010-2014
Atmos: all-sky radiation, diagnostic EDMF, 0-moment microphysics, no aerosols and rrtmg default ozone
Land: bucket

### Stretch target
Resolution: h_elem = 30 (~100km), z_elem = 63
Simulation year: 2005-2014
Atmos: all-sky radiation, diagnostic EDMF, 1-moment microphysics, prescribed aerosols and ozone (with radiation)
Land: bucket

### Tasks

```[tasklist]
### Simulation
- [ ] https://github.com/CliMA/ClimaModules-Derecho/issues/1
- [x] 5-year helem 16 diagnostic EDMF + 0M
- [x] 5-year helem 16 diagnostic EDMF + 0M + better cloud diagnostics
- [ ] 5-year helem 16 diagnostic EDMF + 0M + better cloud diagnostics + aerosols
```
```[tasklist]
### Implementation
- [ ] https://github.com/CliMA/ClimaArtifacts/pull/23
- [ ] https://github.com/CliMA/ClimaCoupler.jl/pull/846
- [ ] https://github.com/CliMA/ClimaAtmos.jl/pull/3019
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/849
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/764
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/860
- [ ] https://github.com/CliMA/RRTMGP.jl/pull/510
- [ ] https://github.com/CliMA/ClimaAtmos.jl/pull/3126
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/3140
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/724
```
```[tasklist]
### Package update
- [ ] https://github.com/CliMA/ClimaAtmos.jl/pull/3098
- [ ] https://github.com/CliMA/ClimaAtmos.jl/pull/3114
- [ ] https://github.com/CliMA/ClimaCoupler.jl/pull/864
- [ ] https://github.com/CliMA/ClimaCoupler.jl/pull/868
```
```[tasklist]
### Issues
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/851
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/869
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/3110
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/858
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/865
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/3113
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/876
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/3105
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/687
- [ ] Stabilize 1M run without EDMF
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/3094
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/571
```

**Comment by szy21** [comment]
cc @tapios

**Comment by tapios** [comment]
> cc @tapios

I'd prefer the option 2 configuration, even it's for a shorter simulation (5 years).

**Comment by szy21** [comment]
> I'd prefer the option 2 configuration, even it's for a shorter simulation (5 years).

Sounds good. I'll see if I can get 1-moment microphysics to run stably by the end of this week. And if I can get someone to work on prescribing ozone then it's possible (although for a five-year simulation I don't think there would be much difference in the statistics between prescribed or default ozone profile?).

**Comment by tapios** [comment]
Ozone variations with latitude would be good to have, but it's not crucial relative to, say, EDMF.

**Comment by szy21** [comment]
Here are some plots from the 5-year diagnostic edmf and 0-moment microphysics simulation:
![image](https://github.com/CliMA/ClimaCoupler.jl/assets/11598433/802cbe6c-ce6a-4acb-9fb8-1240734595ef) ![image](https://github.com/CliMA/ClimaCoupler.jl/assets/11598433/88e03cb4-9198-4e68-b2c9-f266e4d242d3)
![image](https://github.com/CliMA/ClimaCoupler.jl/assets/11598433/44f837ae-a2ea-4484-bf77-a93bd8eb6329) ![image](https://github.com/CliMA/ClimaCoupler.jl/assets/11598433/f877eeaf-7b27-4c8b-9aa1-083baa0d0744)

I will close this issue soon and move the remaining tasks elsewhere.
