### ISSUE TITLE
O1.5.2e Run AMIP simulation with 1M microphysics

### ISSUE THREAD

**Issue by trontrytel** [CliMA/ClimaCoupler.jl#913]
# The Climate Modeling Alliance
### Purpose
Demonstrate a stable multiyear aquaplanet simulation with 1-moment microphysics and cloud diagnostics.

### People and Personnel
- Lead: @trontrytel 
- Collaborators: @akshaysridhar , @szy21 
- Reviewers: -->

### Task Breakdown And Schedule

```[tasklist]
### Implementation
- [x] Do a CloudMicrophysics.jl release
- [x] Update the ClimaAtmos interface
- [x] Delete the old 1-moment microphysics code in the old EDMF code
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/2103
- [ ] https://github.com/CliMA/ClimaAtmos.jl/pull/2400
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/2054
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/2653
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/2654
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/2655
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/2656
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/2657
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/2433
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/2658
```

```[tasklist]
### Test cases
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/2432 (1M + clear-sky radiation)
- [ ] 1M + all-sky radiation
```

### CC
@tapios @simonbyrne @cmbengue

**Comment by szy21** [comment]
@trontrytel The aquaplanet with 1M without topography runs for 360 days now in atmos longrun: https://buildkite.com/clima/climaatmos-gpulongruns/builds/345#01918255-94fa-49ea-966a-935a19620e97. There are still issues with the run with topography so more parameters need to be tuned, but I would suggest that we try the AMIP with 1M now to see if there are any obvious issues.

**Comment by akshaysridhar** [comment]
> @trontrytel The aquaplanet with 1M without topography runs for 360 days now in atmos longrun: https://buildkite.com/clima/climaatmos-gpulongruns/builds/345#01918255-94fa-49ea-966a-935a19620e97. There are still issues with the run with topography so more parameters need to be tuned, but I would suggest that we try the AMIP with 1M now to see if there are any obvious issues.

@trontrytel  @szy21 Following some quick checks against the `AMIP + 1M` configuration (without topography) in the ClimaCoupler; I see that the simulation fails after around 5d16h with the latest ClimaAtmos (main) / Coupler (release) versions. The corresponding `0M` case also fails during the spin-up period at around 2d20h. I'll get more frequent outputs in raw / nc formats and we can look over them over the course of this week.

**Comment by szy21** [comment]
Thanks. Could you focus on 0M? @trontrytel  can take over 1M. I suggest we go directly to AMIP with topography and reduce complexity if things don't work, but it's up to you what hierarchy of simulations you want to test.
