### ISSUE TITLE
O1.5.2d Run AMIP simulation with 0M microphysics

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaCoupler.jl#914]
# The Climate Modeling Alliance
### Purpose

Demonstrate stable multiyear simulations with Earth topography in an AMIP configuration with simple land model. The atmosphere physical process should include time-varying insolation, all-sky radiation with correct cloud diagnostics, Monin-Obukhov surface fluxes and 0M microphysics.

### People and Personnel

- Lead: @akshaysridhar  
- Collaborators: @szy21 @LenkaNovak @kmdeck 
- Reviewers:

### Results and Deliverables

- [ ] Aquaplanet simulation with topography
- [ ] AMIP simulation

### Task Breakdown And Schedule
```[tasklist]
### Topography
- [ ] CliMA/ClimaAtmos.jl#1786
- [ ] CliMA/ClimaAtmos.jl#1846
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/2014
- [ ] Verify longrun configuration with 1M microphysics
```

### CC
@tapios @simonbyrne @cmbengue
@akshaysridhar Please add details. Also feel free to create a corresponding SDI in ClimaCoupler.

**Comment by szy21** [comment]
@akshaysridhar The aquaplanet with 0M and topography runs for longer now but breaks after 300 days in the most recent atmos longrun build: https://buildkite.com/clima/climaatmos-gpulongruns/builds/345#01918255-94f8-401b-afdf-63138871037a. Could you take a look at why it breaks and what else can be changed? Otherwise I am fine with putting it on hold and moving to AMIP too.

**Comment by szy21** [comment]
@akshaysridhar FYI the aquaplanet with 0M and topography run breaks after 150 days in the most recent build: https://buildkite.com/clima/climaatmos-gpulongruns/builds/380#0191a661-334c-47bc-b876-5ccac46f8599. Has anything changed last week? Or is this job non-deterministic?

**Comment by akshaysridhar** [comment]
> @akshaysridhar FYI the aquaplanet with 0M and topography run breaks after 150 days in the most recent build: https://buildkite.com/clima/climaatmos-gpulongruns/builds/380#0191a661-334c-47bc-b876-5ccac46f8599. Has anything changed last week? Or is this job non-deterministic?

No additional PRs related to the diffusion updates were merged (following the longrun build triggered during the 24Aug weekend): I expect this to be deterministic based on last week's PRs. I'll flag it for checks once I am back.
